from pathlib import Path
from datetime import datetime, timedelta
import random

REPORTS_DIR = Path("reports")
REPORTS_DIR.mkdir(parents=True, exist_ok=True)

def generate_mock_report(date_obj, score):
    timestamp = date_obj.strftime("%Y-%m-%d_%H-%M-%S")
    date_str = date_obj.strftime("%Y-%m-%d")
    time_str = date_obj.strftime("%H:%M:%S")
    
    report_content = f"""# AI Review Report

## Report Metadata

- Repository name: applet
- Current branch: master
- Generated by: Daily AI Review
- Gemini model: gemini-1.5-flash

## Review Information

- Date: {date_str}
- Time: {time_str}
- Review Mode: all
- Execution Time: {random.uniform(5.0, 15.0):.2f} seconds

## Repository Summary

- Files discovered: 50
- Files reviewed: 50
- Files changed: {int((100-score)/2)}
- Files skipped: 0
- Files failed: 0
- Success rate: 100.00%

## Repository Health

Overall Score : {score}

Documentation : {score + random.randint(-5, 5)}
Code Quality : {score + random.randint(-5, 5)}
Maintainability : {score + random.randint(-5, 5)}
Architecture : {score + random.randint(-5, 5)}
Naming : {score + random.randint(-5, 5)}

## Review Totals

Files Reviewed: 50
Files Modified: {int((100-score)/2)}
Files Skipped: 0
Files Failed: 0
Success Rate: 100.00%
Execution Time: 10.00 seconds
"""
    file_path = REPORTS_DIR / f"{timestamp}_review.md"
    file_path.write_text(report_content)
    print(f"Generated {file_path} with score {score}")

now = datetime.now()
scores = [85, 88, 82, 90, 95]
for i, score in enumerate(scores):
    date_obj = now - timedelta(days=(len(scores) - i))
    generate_mock_report(date_obj, score)
